config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help'  =>'static_pages#help'
  get 'home'  =>'static_pages#home'
  get 'about'=> 'static_pages#about'
  get 'contact'=> 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'users/show'=>'users#show'
  get 'login'=>'sessions#new'
  post 'login'=>'sessions#create'
  delete 'logout'=>'sessions#destroy'

  resources :users
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user= User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me]=='1'?remember(user):forget(user)
      redirect_to redirect_back_or user
    else
      flash.now[:danger]="Invalid email/password combination! "
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
    
  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,only:[:edit,:update]
  before_action :correct_user,only:[:edit,:update]
  def new
  end
  def correct_user
    @user=User.find(params[:id])
    redirect_to(root_url) unless current_user? @user
  end
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger]="Please log in"
      redirect_to login_url
    end
  end

  def show
    @user=User.find(params[:id])
    puts @user_
  end

  def new
    @user=User.new
  end

  def create
    #debugger
    @user=User.new(user_params)
    if(@user.save)
      log_in @user
      flash[:success]="Welcome to the Sample App"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success]="Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title="Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  #logs in the current user
  def log_in(user)
    session[:user_id]=user.id
  end

  #get current logged-in user
  def current_user
    if (user_id=session[:user_id])
      @current_user||= User.find_by(id: session[:user_id])
    elsif (user_id=cookies.signed[:user_id])
      #next time when log in, can get user information from cookies
      user=User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user=user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    #add by fionhan on 2015-5-20 to clear cookies in broswer,
    # because if not, :user_id will not be nil and session[:user_id] will always not be nil,
    #so the user will never log out,and the user_login_test.rb faild
    forget current_user if !current_user.nil?
    session.delete(:user_id)
    @current_user=nil
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id]=user.id
    cookies.permanent[:remember_token]=user.remember_token
  end

  # Forgets a persistent user information in cookies
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def current_user?(user)
    user==current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url]=request.url if request.get
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  #Return gravatar for the given user
  def gravatar_for(user,size="50*50")
    gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}"
    if size.empty?
    image_tag(gravatar_url,alt:user.name,class:"gravatar")
    else
    image_tag(gravatar_url,alt:user.name,class:"gravatar",size:size)
  end
  end
  end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",
                      '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",'home' %></li>
        <li><%= link_to "Help",'help' %></li>
        <% if logged_in? %>
            <li><%= link_to 'Users', '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class:"alert alert-#{message_type}") %>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <% debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@user.errors.count,"error")%>.
        </div>
      <ul>
        <% @user.errors.full_messages.each do |msg|%>
        <li><%= msg%></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title,"About")%>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | Ruby On Rails Tutorial Sample App</title>
</head>
<body>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact")%>
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%> | Ruby On Rails Tutorial Sample App</title>
</head>
<body>
<h1>Contact</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.
  This is the sample application for the tutorial.
</p>
</body>
</html>

app/views/static_pages/help.html.erb
<%provide(:title,"Help")%>
<!DOCTYPE html>
<html>
<head>
  <title><%=yield(:title)%> | Ruby On Rails Tutorial Sample App</title>
</head>
<body>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help
    section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails
    Tutorial</em> book</a>.
</p>
</body>
</html>

app/views/static_pages/home.html.erb
<h1>Sample App</h1>
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1 class="sign-up">Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages' %>
        <%= f.label :name %>
        <%= f.text_field :name,class:'form-control' %>
        <%= f.label :email %>
        <%= f.email_field :email,class:'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password,class:'form-control' %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation,class:'form-control' %>
        <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%provide(:title,@user.name)%>

<div class="row">
<aside class="col-md-4">
  <section class="user-info" >
    <h1>
      <%= gravatar_for @user,"50x50"%>
      <%=@user.name%>
    </h1>
  </section>
</aside>
</div>